AwesomeMoviesApp/force-app/main/default/objects/Actor__c/Actor__c.object-meta.xml
<CustomObject>
    <label>Actor</label>
    <nameField>
        <label>Actor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AwesomeMoviesApp/force-app/main/default/objects/Actor__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
                <default>true</default>
                <label>Male</label>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

AwesomeMoviesApp/force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AwesomeMoviesApp/force-app/main/default/objects/MovieActor__c/MovieActor__c.object-meta.xml
<CustomObject>
    <label>MovieActor</label>
    <nameField>
        <label>MovieActor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MovieActors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AwesomeMoviesApp/force-app/main/default/objects/MovieActor__c/fields/Actor__c.field-meta.xml
<CustomField>
    <fullName>Actor__c</fullName>
    <label>Actor</label>
    <referenceTo>Actor__c</referenceTo>
    <relationshipLabel>Movies</relationshipLabel>
    <relationshipName>MovieActors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

AwesomeMoviesApp/force-app/main/default/objects/MovieActor__c/fields/Movie__c.field-meta.xml
<CustomField>
    <fullName>Movie__c</fullName>
    <label>Movie</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>Actors</relationshipLabel>
    <relationshipName>MovieActors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

AwesomeMoviesApp/force-app/main/default/classes/MovieActorTriggerHelper.cls
public with sharing class MovieActorTriggerHelper {
    public static void updateMovieMaleAndFemalePercentage(List<MovieActor__c> newMovieActors){
        // business logic
        Integer malePourcentage = 0;
        Integer feMalePourcentage = 0;
        
         for(MovieActor__c movieActor : newMovieActors) {

            Actor__c actor = [SELECT Gender__c , Number_of_movies__c FROM Actor__c WHERE Actor__c.Id = :movieActor.Actor__c ];

            if(actor.Gender__c.equalsIgnoreCase('male')){
                malePourcentage++;
            }else{
                feMalePourcentage++;
            }

            actor.Number_of_movies__c ++;
            update actor;
        } 

        Movie__c movie  = [SELECT MaleActorsPercentage__c, FeMaleActorsPercentage__c FROM Movie__c WHERE Movie__c.Id =: newMovieActors.get(0).Movie__c];
       
        movie.MaleActorsPercentage__c = (malePourcentage / malePourcentage + feMalePourcentage)*100;
        movie.FeMaleActorsPercentage__c =(feMalePourcentage / malePourcentage + feMalePourcentage)*100;
        
        update movie;
    }
}